name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can change this to your desired Java version
        distribution: 'adopt' # Specify the distribution here (e.g., adopt, adopt-jdk)


    - name: Compile and run Java code
      run: |
        cd lms
        echo "Packaging the lms app.."
        javac *.java models/*.java
        jar cfm lms.jar manifest.txt *.class models/
        ls -al
