name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '20' # You can change this to your desired Java version

    - name: Compile and run Java code
      run: |
        cd oops/polymorphism
        javac Bookstore.java
        java Bookstore
